# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 619f7ec9b8070dcde913c7328ae1a29daa130f719dac864856e10ad67454346907755f7c38dc103e01f2887172c65c6a5f7ba0562d7ddadc7b9cd3ffd3061cbe

test:
  secret_key_base: 2724151188a55bf2a7da70df36a03a513f49a535088370cb9e5a3fd287b56820ca272a6190273a1dd31ec36f840d7861fed20c3bbfe10720a4f5c66404e287b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
